<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product_storage extends Model
{
    use HasFactory;
    protected $table = 'software';
    protected $fillable = [
        'user_id',
        'category_id',
        'sub_category_id',
        'amount_eg',
        'image',
        'amount',
        'product_type',
        'title',
        'product_code',
        'product_country',
        'available_in_country',
        'wp_product',
        'slug',
        'permalink',
        'date_created',
        'date_created_gmt',
        'date_modified',
        'date_modified_gmt',
        'shipping_charge',
        'type',
        'status',
        'featured',
        'catalog_visibility',
        'description',
        'short_description',
        'price',
        'regular_price',
        'sale_price',
        'date_on_sale_from',
        'date_on_sale_from_gmt',
        'date_on_sale_to',
        'date_on_sale_to_gmt',
        'on_sale',
        'purchasable',
        'total_sales',
        'virtual',
        'downloadable',
        'download_limit',
        'download_expiry',
        'external_url',
        'button_text',
        'tax_status',
        'tax_class',
        'manage_stock',
        'stock_quantity',
        'backorders',
        'backorders_allowed',
        'backordered',
        'low_stock_amount',
        'sold_individually',
        'weight',
        'dimensions',
        'shipping_required',
        'shipping_taxable',
        'shipping_class',
        'shipping_class_id',
        'reviews_allowed',
        'average',
        'rating_count',
        'upsell_ids',
        'cross_sell_ids',
        'parent_id',
        'purchase_note',
        'tag',
        'menu_order',
        'price_html',
        'stock_status',
        'has_options',
        'post_password',
        'recommand_seling_price',
        'delivery_day',
    ];
}
